- hosts: nexus
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
  - roles/nexus/vars/main.yml
  handlers:
  - include: roles/nexus/handlers/main.yml
  roles:
  - role: roles/nexus



- hosts: sonarqube
  gather_facts: false
  become: yes
  become_method: sudo
  remote_user: ubuntu
  vars_files:
  - roles/sonarqube/vars/main.yml
  handlers:
  - include: roles/sonarqube/handlers/main.yml
  roles:
  - role: roles/sonarqube