- name: Install apache
  hosts: ec2
  become: true
  tasks:
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest
       

    - name: Change default Apache port
      lineinfile:
             path: /etc/apache2/ports.conf
             regexp: '^Listen.*'
             line: 'Listen 8090'
             state: present
  
  
  
    - name: Configure To My HTML page
      copy:
            src: /home/alimarawan/Ansible/ali.html
            dest: /var/www/html/index.html
            mode: 0644


    - name: Restart Apache
      service:
            name: apache2
            state: restarted
